# Setup
title:               Wenhao Deng
tagline:             ''
description:         ''
url:                 https://w3nhao.github.io
baseurl:             ''
permalink:           pretty

# About/contact
author:
  name:              Wenhao Deng
  url:               https://github.com/w3nhao
  email:             wenhao.deng@foxmail.com

# Gems
plugins:
  - jekyll-paginate-v2
  - jekyll-toc
  - jekyll-spaceship

# Exclude hidden posts from pagination by default (safety for some generators)
# We still filter in templates, but this flag can be checked in custom logic
hidden_posts_tag: hidden

pagination:
  enabled: true
  per_page: 5
  permalink: '/posts/page/:num/'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

toc:
  min_level: 1
  max_level: 6
  marker: "<!-- toc -->"
  list_class: "toc__list"
  sublist_class: "toc__sublist"
  item_class: "toc__item"
  link_class: "toc__link"
  list_tag: "ul"
  sublist_tag: "ul"
  item_tag: "li"
  link_tag: "a"
  range_start: "<!-- toc:start -->"
  range_end: "<!-- toc:end -->"

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
